org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.158.0+26.2

# Mod Properties
mod_version=0.1.0
maven_group=me.justbecause.distantdecorations
archives_base_name=distant-decorations

# Optional Dependencies
chunky_version=DCgX52a5
voxy_version=zZX86mbc
sodium_version=mc26.2-0.9.2-alpha.3-fabric
